### ISSUE TITLE
Error message after a few days of running this exporter

### ISSUE THREAD

**Issue by netmax79** [mulbc/fritzdocsis#1]
After a few days of running this exporter it died unexpected. During startup it printed out following error message:

FATA[0000] Issues getting fritzbox response              error="json: cannot unmarshal number 2.28354e+09 into Go struct field .data.channelDs.docsis30.corrErrors of type int

I check my fritz box panel for the counter values and saw that there are some values quite high, this lead me to the assumption that
int might be to small to save the values.

As i'm not familiar with golang, i first tried with int64, but this didn't work either. I then tried float64 instead which seems to work well for me.

I will create a pull request for this.

**Comment by mulbc** [comment]
Thanks for checking out my project and glad it's useful for you... I just also updated the Grafana Dashboard which might be interesting to you ;)
