### ISSUE TITLE
A ready built docker image?

### ISSUE THREAD

**Issue by Technikte** [mulbc/fritzdocsis#3]
Is it possible to get a ready to run docker image with this scraper ?
I am quite lost at the moment to build your nice scraper and run prometheus and so on.

**Comment by mulbc** [comment]
If you don't know about Prometheus, maybe this tool isn't for you.
If you are willing to invest the time to learn about Prometheus though, I suggest going through this: https://prometheus.io/docs/introduction/first_steps/

You can then proceed to running Prometheus in a docker: https://hub.docker.com/r/prom/prometheus

Once you've done that, you probably learned so much that you know how to start this exporter and hook it up into Prometheus, if not, let me know and I'll give you some more help

**Comment by Technikte** [comment]
Well, some time has passed.
I am already running prometheus, grafana and much more inside container in docker but most/all times it was easy as docker pull image-xx:latest. I kinda struggle how to get your project into a ready to go docker image, a more or less ready to build docker file would be very good.

**Comment by mulbc** [comment]
I've made a container image available for you. I don't promise that this will receive any updates though ;)

Run the image like this:

```
docker run --rm -p 2112:2112 quay.io/mulbc/fritzdocsis -username USER -password PASS -url http://FRITZBOX
```

You can then get the metrics at http://localhost:2112/metrics
