### ISSUE TITLE
dockerfile

### ISSUE THREAD

**Issue by Technikte** [mulbc/fritzdocsis#5]
Hi there,
is it possible that you can turn your project into a dockerfile which then I could use to build a image, locally to run ?
I dont have the skills to do it really.

I looked at ... to get a feeling but everything I try fails more or less.
https://docs.docker.com/language/golang/build-images/
https://github.com/codefresh-contrib/golang-sample-app

**Comment by mulbc** [comment]
Let's keep the conversation in #3 - I'll reopen it for you
