### ISSUE TITLE
07.39-96140 BETA on 6660 breaks fritzdocsis

### ISSUE THREAD

**Issue by mightytarzan** [mulbc/fritzdocsis#9]
Seems the JSON encoding has changed. The following diff fixes the issue for me: https://pastebin.com/FsTrJGNT

**Comment by Technikte** [comment]
Yes, the same happens on 07.39-95784 BETA
Fix https://github.com/mulbc/fritzdocsis/pull/10

**Comment by mulbc** [comment]
Fixed by release [v0.3.0](https://github.com/mulbc/fritzdocsis/releases/tag/v0.3.0)
